### PR TITLE
Closes https://github.com/Lokathor/tinyvec/issues/75

### LINKED ISSUE #75: Error inferring array type when using tiny_vec! with variables
Adding this test:
```rust
#[test]
fn TinyVec_macro_variables_inference() {
  let x = 4i32;
  let y = 5i32;
  let _: TinyVec<[i32; 10]> = tiny_vec!(x, y);
}
```
Produces this error:
```
error[E0435]: attempt to use a non-constant value in a constant
   --> tests\tinyvec.rs:108:41
    |
108 |   let _: TinyVec<[i32; 10]> = tiny_vec!(x, y);
    |                                         ^ non-constant value
```
I believe `x` is assumed to be a const generic parameter, or some such.

### PR DESCRIPTION
**Pull request by Lokathor**
This fixes #75, and also the ArraySet type is now included behind a feature gate.

### CODE REVIEW

**Comment by Lokathor** [comment]
@ThatsNoMoon

File: src/arrayset.rs [hunk 1]
```diff
@@ -26,266 +32,274 @@ impl fmt::Display for InsertError {
...
+      if arr[i].borrow() == elt {
+        let l1 = len - 1;
+        if i < l1 {
+          arr.swap(i, l1);
         }
-        None
+        self.len -= L::from(1);
+        let mut r = Default::default();
+        swap(&mut arr[l1], &mut r);
+        return Some(r);
```
Comment (Nemo157) [inline src/arrayset.rs:139]: Since it's experimental, may as well bypass the min-rust version :wink: 

```suggestion
        return Some(std::mem::take(&mut arr[l1]));
```

But otherwise, `replace` is still better

```suggestion
        return Some(std::mem::replace(&mut arr[l1], <A::Item>::default()));
```

Comment (Lokathor) [reply src/arrayset.rs:139]: Actually I think we have a custom `take` in our lib.rs to support taking even with our older version.
